version: "3.8"

services:
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    # env_file: .env
    networks:
      app:
  web:
    build: ./web
    ports:
      - 8080:80
    environment:
      - PASTPATH_DB_PORT=5436
    env_file:
      - ./local.env
    volumes:
      - ./web:/app
    depends_on:
      - db
    networks:
      app:
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: -p 5436
    networks:
      app:
networks:
  app:
